chore: set php version to 8.3

diff --git a/.github/workflows/php-stan.yml b/.github/workflows/php-stan.yml
--- a/.github/workflows/php-stan.yml
+++ b/.github/workflows/php-stan.yml
@@ -8,11 +8,6 @@ on:
         type: number
         required: true
         default: 0
-      PHP_VERSION:
-        description: 'PHP Version used by the project'
-        type: number
-        required: true
-        default: 8.3 
       STOP_ON_ERROR:
         description: 'Stop on error'
         type: boolean
@@ -33,7 +28,7 @@ jobs:
     strategy:
       fail-fast: true
       matrix:
-        php: [${{input.PHP_VERSION}}]
+        php: [8.3]
 
     steps:
       - name: Checkout code
@@ -46,31 +41,30 @@ jobs:
           extensions: json, dom, curl, libxml, mbstring
           coverage: none
 
+      - name: Install dependencies
+        run: composer install --prefer-dist --no-progress
 
-    - name: Install dependencies
-      run: composer install --prefer-dist --no-progress
+      - name: Run PHP Stan and save output to file
+        uses: GuillaumeFalourd/command-output-file-action@v1.1
+        with:
+          command_line: vendor/bin/phpstan --no-progress --error-format=github  analyse -l ${{inputs.PHP_STAN_LEVEL}} src
+          output_file_name: phpstan.txt
 
-    - name: Run PHP Stan and save output to file
-      uses: GuillaumeFalourd/command-output-file-action@v1.1
-      with:
-        command_line: vendor/bin/phpstan --no-progress --error-format=github  analyse -l ${{inputs.PHP_STAN_LEVEL}} src
-        output_file_name: phpstan.txt
+      - name: Read PHP Stan errors and save count to PHP_STAN_ERRORS_COUNT
+        run: |
+          echo "PHP_STAN_ERRORS_COUNT=$(cat ./phpstan.txt | grep -o -i ::error | wc -w)" >> $GITHUB_ENV
+        continue-on-error: true
 
-    - name: Read PHP Stan errors and save count to PHP_STAN_ERRORS_COUNT
-      run: |
-        echo "PHP_STAN_ERRORS_COUNT=$(cat ./phpstan.txt | grep -o -i ::error | wc -w)" >> $GITHUB_ENV
-      continue-on-error: true
-    
-    - name: Comment PR if there are PHP Stan errors
-      if: env.PHP_STAN_ERRORS_COUNT > 0
-      uses: thollander/actions-comment-pull-request@v2
-      with:
-        message: |
-          PHPStan -> ${{env.PHP_STAN_ERRORS_COUNT}} errors found. Please fix them before merging.
-        comment_tag: phpstan
-        mode: recreate
+      - name: Comment PR if there are PHP Stan errors
+        if: env.PHP_STAN_ERRORS_COUNT > 0
+        uses: thollander/actions-comment-pull-request@v2
+        with:
+          message: |
+            PHPStan -> ${{env.PHP_STAN_ERRORS_COUNT}} errors found. Please fix them before merging.
+          comment_tag: phpstan
+          mode: recreate
 
-    - name: Break if there are PHP Stan errors
-      if: inputs.STOP_ON_ERROR == true
-      run: |
-        if [ ${{env.PHP_STAN_ERRORS_COUNT}} -gt 0 ]; then exit 1; fi
+      - name: Break if there are PHP Stan errors
+        if: inputs.STOP_ON_ERROR == true
+        run: |
+          if [ ${{env.PHP_STAN_ERRORS_COUNT}} -gt 0 ]; then exit 1; fi
